In [6]:
import numpy as np
a=np.array([1,2,3,4,5])
print("One dimensional array:",a)

One dimensional array: [1 2 3 4 5]


In [8]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print("2 dimensional array:",b)

2 dimensional array: [[1 2 3 4]
 [5 6 7 8]]


In [9]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
d=np.random.random((3,3))
print(d)

[[0.32670799 0.25635024 0.14081973]
 [0.92884538 0.73166141 0.99120534]
 [0.64134049 0.15527614 0.17950473]]


In [11]:
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]
