In [1]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[6,2,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[10 20 30 40 50]
[6 2 9 7 1]
[16 22 39 47 51]
[ 4 18 21 33 49]
[ 60  40 270 280  50]
[ 1.66666667 10.          3.33333333  5.71428571 50.        ]


In [2]:
print(a.dot(b))

700


In [3]:
sclr=3
print("Scalar value:",sclr)
print("Array:",a)
print("Result:",a*sclr)

Scalar value: 3
Array: [10 20 30 40 50]
Result: [ 30  60  90 120 150]


In [5]:
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [15]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[10,20,30,40]
arr2=[2,10,35,25]
print("array1:",arr1)
print("array2:",arr2)
vect_func=np.vectorize(my_func)
print("Result:",vect_func(arr1,arr2))

array1: [10, 20, 30, 40]
array2: [2, 10, 35, 25]
Result: [ 8 10 65 15]
