In [4]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [12]:
flat=arr.flatten()
print(arr)
print(flat)


[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [13]:
print(arr.ndim)

2


In [14]:
print(arr.shape)


(3, 4)


In [15]:
print(arr.dtype)

int64


In [16]:
newtype=arr.astype('f')
print("\n convert array:\n",newtype)
print("\n converted array type:\n",newtype.dtype)


 convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 converted array type:
 float32


In [17]:
size=len(arr)
print("\nsizeofarray:\n",size)


sizeofarray:
 3
